name: .NET SDKs

on:
  push:
    branches: [main]
  pull_request:

env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  install-sdks:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

    steps:
      - run: dotnet --info

      - name: Set up .NET
        uses: actions/setup-dotnet@v2.0.0
        with:
          dotnet-version: |
            3.1.417
            5.0.406
            6.0.201

      - run: dotnet --info

      - name: Set up .NET
        uses: actions/setup-dotnet@v2.0.0
        with:
          dotnet-version: |
            3.1.417
            5.0.406
            6.0.201

      - run: dotnet --info
